repos:
  # Python Formatting (Black)
  - repo: https://github.com/psf/black
    rev: 25.11.0
    hooks:
      - id: black
        # Black is highly opinionated, so no arguments needed unless you have a custom line-length

  # General Web Formatting
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

    # JavaScript/TypeScript/HTML/CSS Formatting (Prettier)
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        # Prettier will automatically format files like .js, .ts, .jsx, .tsx, .html, .css, .scss, .json, .md, etc.
